name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
            sudo bash -c "${{ github.workspace }}/build.sh"

      - name: Build-musl
        uses: countstarlight/arch-makepkg-action@master
        with:
          #repos: >
          #  archlinuxcn=https://geo-mirror.chaotic.cx/$repo/$arch
          #before: "sudo pacman -S --noconfirm archlinux-keyring chaotic-keyring chaotic-mirrorlist"
          packages: >
            musl
          #   base-devel
          #   coreutils
          #   curl
          #   upx
          scripts: "./build-musl.sh"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: procps-static-*.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
